### Data Loading

In [1]:
import numpy as np
import pandas as pd

df = pd.read_csv('compas-scores.csv')
df

,id,name,first,last,compas_screening_date,sex,dob,age,age_cat,race,...,vr_offense_date,vr_charge_desc,v_type_of_assessment,v_decile_score,v_score_text,v_screening_date,type_of_assessment,decile_score.1,score_text,screening_date
0,1,miguel hernandez,miguel,hernandez,2013-08-14,Male,1947-04-18,69,Greater than 45,Other,...,NaN,NaN,Risk of Violence,1,Low,2013-08-14,Risk of Recidivism,1,Low,2013-08-14
1,2,michael ryan,michael,ryan,2014-12-31,Male,1985-02-06,31,25 - 45,Caucasian,...,NaN,NaN,Risk of Violence,2,Low,2014-12-31,Risk of Recidivism,5,Medium,2014-12-31
2,3,kevon dixon,kevon,dixon,2013-01-27,Male,1982-01-22,34,25 - 45,African-American,...,2013-07-05,Felony Battery (Dom Strang),Risk of Violence,1,Low,2013-01-27,Risk of Recidivism,3,Low,2013-01-27
3,4,ed philo,ed,philo,2013-04-14,Male,1991-05-14,24,Less than 25,African-American,...,NaN,NaN,Risk of Violence,3,Low,2013-04-14,Risk of Recidivism,4,Low,2013-04-14
4,5,marcu brown,marcu,brown,2013-01-13,Male,1993-01-21,23,Less than 25,African-American,...,NaN,NaN,Risk of Violence,6,Medium,2013-01-13,Risk of Recidivism,8,High,2013-01-13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11752,11753,patrick hamilton,patrick,hamilton,2013-09-22,Male,1968-05-02,47,Greater than 45,Other,...,NaN,NaN,Risk of Violence,1,Low,2013-09-22,Risk of Recidivism,3,Low,2013-09-22
11753,11754,raymond hernandez,raymond,hernandez,2013-05-17,Male,1993-06-24,22,Less than 25,Caucasian,...,NaN,NaN,Risk of Violence,5,Medium,2013-05-17,Risk of Recidivism,7,Medium,2013-05-17
11754,11755,dieuseul pierre-gilles,dieuseul,pierre-gilles,2014-10-08,Male,1981-01-24,35,25 - 45,Other,...,NaN,NaN,Risk of Violence,3,Low,2014-10-08,Risk of Recidivism,4,Low,2014-10-08
11755,11756,scott lomagistro,scott,lomagistro,2013-12-03,Male,1986-12-04,29,25 - 45,Caucasian,...,NaN,NaN,Risk of Violence,2,Low,2013-12-03,Risk of Recidivism,3,Low,2013-12-03
11756,11757,chin yan,chin,yan,2014-01-11,Male,1982-02-19,34,25 - 45,Asian,...,NaN,NaN,Risk of Violence,1,Low,2014-01-11,Risk of Recidivism,1,Low,2014-01-11

In [2]:
df = df[df['is_recid']!=-1]
df = df[df['decile_score']!=-1]
df

,id,name,first,last,compas_screening_date,sex,dob,age,age_cat,race,...,vr_offense_date,vr_charge_desc,v_type_of_assessment,v_decile_score,v_score_text,v_screening_date,type_of_assessment,decile_score.1,score_text,screening_date
0,1,miguel hernandez,miguel,hernandez,2013-08-14,Male,1947-04-18,69,Greater than 45,Other,...,NaN,NaN,Risk of Violence,1,Low,2013-08-14,Risk of Recidivism,1,Low,2013-08-14
2,3,kevon dixon,kevon,dixon,2013-01-27,Male,1982-01-22,34,25 - 45,African-American,...,2013-07-05,Felony Battery (Dom Strang),Risk of Violence,1,Low,2013-01-27,Risk of Recidivism,3,Low,2013-01-27
3,4,ed philo,ed,philo,2013-04-14,Male,1991-05-14,24,Less than 25,African-American,...,NaN,NaN,Risk of Violence,3,Low,2013-04-14,Risk of Recidivism,4,Low,2013-04-14
4,5,marcu brown,marcu,brown,2013-01-13,Male,1993-01-21,23,Less than 25,African-American,...,NaN,NaN,Risk of Violence,6,Medium,2013-01-13,Risk of Recidivism,8,High,2013-01-13
5,6,bouthy pierrelouis,bouthy,pierrelouis,2013-03-26,Male,1973-01-22,43,25 - 45,Other,...,NaN,NaN,Risk of Violence,1,Low,2013-03-26,Risk of Recidivism,1,Low,2013-03-26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11752,11753,patrick hamilton,patrick,hamilton,2013-09-22,Male,1968-05-02,47,Greater than 45,Other,...,NaN,NaN,Risk of Violence,1,Low,2013-09-22,Risk of Recidivism,3,Low,2013-09-22
11753,11754,raymond hernandez,raymond,hernandez,2013-05-17,Male,1993-06-24,22,Less than 25,Caucasian,...,NaN,NaN,Risk of Violence,5,Medium,2013-05-17,Risk of Recidivism,7,Medium,2013-05-17
11754,11755,dieuseul pierre-gilles,dieuseul,pierre-gilles,2014-10-08,Male,1981-01-24,35,25 - 45,Other,...,NaN,NaN,Risk of Violence,3,Low,2014-10-08,Risk of Recidivism,4,Low,2014-10-08
11755,11756,scott lomagistro,scott,lomagistro,2013-12-03,Male,1986-12-04,29,25 - 45,Caucasian,...,NaN,NaN,Risk of Violence,2,Low,2013-12-03,Risk of Recidivism,3,Low,2013-12-03
11756,11757,chin yan,chin,yan,2014-01-11,Male,1982-02-19,34,25 - 45,Asian,...,NaN,NaN,Risk of Violence,1,Low,2014-01-11,Risk of Recidivism,1,Low,2014-01-11

### Create Adjacency Matrix

In [3]:
df['c_jail_in']= pd.to_datetime(df['c_jail_in'])
df['c_jail_out']= pd.to_datetime(df['c_jail_out'])

In [4]:
df = df.dropna(axis=0,subset=['c_jail_in'])
df = df.dropna(axis=0,subset=['c_jail_out'])
df = df.reset_index()
df = df.drop(columns=['index'])
df

,id,name,first,last,compas_screening_date,sex,dob,age,age_cat,race,...,vr_offense_date,vr_charge_desc,v_type_of_assessment,v_decile_score,v_score_text,v_screening_date,type_of_assessment,decile_score.1,score_text,screening_date
0,1,miguel hernandez,miguel,hernandez,2013-08-14,Male,1947-04-18,69,Greater than 45,Other,...,NaN,NaN,Risk of Violence,1,Low,2013-08-14,Risk of Recidivism,1,Low,2013-08-14
1,3,kevon dixon,kevon,dixon,2013-01-27,Male,1982-01-22,34,25 - 45,African-American,...,2013-07-05,Felony Battery (Dom Strang),Risk of Violence,1,Low,2013-01-27,Risk of Recidivism,3,Low,2013-01-27
2,4,ed philo,ed,philo,2013-04-14,Male,1991-05-14,24,Less than 25,African-American,...,NaN,NaN,Risk of Violence,3,Low,2013-04-14,Risk of Recidivism,4,Low,2013-04-14
3,7,marsha miles,marsha,miles,2013-11-30,Male,1971-08-22,44,25 - 45,Other,...,NaN,NaN,Risk of Violence,1,Low,2013-11-30,Risk of Recidivism,1,Low,2013-11-30
4,8,edward riddle,edward,riddle,2014-02-19,Male,1974-07-23,41,25 - 45,Caucasian,...,NaN,NaN,Risk of Violence,2,Low,2014-02-19,Risk of Recidivism,6,Medium,2014-02-19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10562,11752,rodrick phillips,rodrick,phillips,2013-02-27,Male,1953-02-24,63,Greater than 45,African-American,...,NaN,NaN,Risk of Violence,1,Low,2013-02-27,Risk of Recidivism,1,Low,2013-02-27
10563,11753,patrick hamilton,patrick,hamilton,2013-09-22,Male,1968-05-02,47,Greater than 45,Other,...,NaN,NaN,Risk of Violence,1,Low,2013-09-22,Risk of Recidivism,3,Low,2013-09-22
10564,11754,raymond hernandez,raymond,hernandez,2013-05-17,Male,1993-06-24,22,Less than 25,Caucasian,...,NaN,NaN,Risk of Violence,5,Medium,2013-05-17,Risk of Recidivism,7,Medium,2013-05-17
10565,11756,scott lomagistro,scott,lomagistro,2013-12-03,Male,1986-12-04,29,25 - 45,Caucasian,...,NaN,NaN,Risk of Violence,2,Low,2013-12-03,Risk of Recidivism,3,Low,2013-12-03
10566,11757,chin yan,chin,yan,2014-01-11,Male,1982-02-19,34,25 - 45,Asian,...,NaN,NaN,Risk of Violence,1,Low,2014-01-11,Risk of Recidivism,1,Low,2014-01-11

In [5]:
from collections import namedtuple

Range = namedtuple('Range', ['start', 'end'])
N = df.shape[0]
matrix = np.zeros((N,N))

for i in range(N):
    r1 = Range(start=df.iloc[i,16],end=df.iloc[i,17])
    if i % 10 == 0:
        print(i)
    for j in range(i+1,N):
        r2 = Range(start=df.iloc[j,16],end=df.iloc[j,17])
        latest_start = max(r1.start, r2.start)
        earliest_end = min(r1.end, r2.end)
        delta = (earliest_end - latest_start).days
        if delta >=0:
            matrix[i,j] = 1
            matrix[j,i] = 1

0
10
20
30
40
50
60
70
80
90
100
110
120
130
140
150
160
170
180
190
200
210
220
230
240
250
260
270
280
290
300
310
320
330
340
350
360
370
380
390
400
410
420
430
440
450
460
470
480
490
500
510
520
530
540
550
560
570
580
590
600
610
620
630
640
650
660
670
680
690
700
710
720
730
740
750
760
770
780
790
800
810
820
830
840
850
860
870
880
890
900
910
920
930
940
950
960
970
980
990
1000
1010
1020
1030
1040
1050
1060
1070
1080
1090
1100
1110
1120
1130
1140
1150
1160
1170
1180
1190
1200
1210
1220
1230
1240
1250
1260
1270
1280
1290
1300
1310
1320
1330
1340
1350
1360
1370
1380
1390
1400
1410
1420
1430
1440
1450
1460
1470
1480
1490
1500
1510
1520
1530
1540
1550
1560
1570
1580
1590
1600
1610
1620
1630
1640
1650
1660
1670
1680
1690
1700
1710
1720
1730
1740
1750
1760
1770
1780
1790
1800
1810
1820
1830
1840
1850
1860
1870
1880
1890
1900
1910
1920
1930
1940
1950
1960
1970
1980
1990
2000
2010
2020
2030
2040
2050
2060
2070
2080
2090
2100
2110
2120
2130
2140
2150
2160
2170
2180
2190
2200
2210
2220
2230
2240
2250
2260
2270
2280
2290
2300
2310
2320
2330
2340
2350
2360
2370
2380
2390
2400
2410
2420
2430
2440
2450
2460
2470
2480
2490
2500
2510
2520
2530
2540
2550
2560
2570
2580
2590
2600
2610
2620
2630
2640
2650
2660
2670
2680
2690
2700
2710
2720
2730
2740
2750
2760
2770
2780
2790
2800
2810
2820
2830
2840
2850
2860
2870
2880
2890
2900
2910
2920
2930
2940
2950
2960
2970
2980
2990
3000
3010
3020
3030
3040
3050
3060
3070
3080
3090
3100
3110
3120
3130
3140
3150
3160
3170
3180
3190
3200
3210
3220
3230
3240
3250
3260
3270
3280
3290
3300
3310
3320
3330
3340
3350
3360
3370
3380
3390
3400
3410
3420
3430
3440
3450
3460
3470
3480
3490
3500
3510
3520
3530
3540
3550
3560
3570
3580
3590
3600
3610
3620
3630
3640
3650
3660
3670
3680
3690
3700
3710
3720
3730
3740
3750
3760
3770
3780
3790
3800
3810
3820
3830
3840
3850
3860
3870
3880
3890
3900
3910
3920
3930
3940
3950
3960
3970
3980
3990
4000
4010
4020
4030
4040
4050
4060
4070
4080
4090
4100
4110
4120
4130
4140
4150
4160
4170
4180
4190
4200
4210
4220
4230
4240
4250
4260
4270
4280
4290
4300
4310
4320
4330
4340
4350
4360
4370
4380
4390
4400
4410
4420
4430
4440
4450
4460
4470
4480
4490
4500
4510
4520
4530
4540
4550
4560
4570
4580
4590
4600
4610
4620
4630
4640
4650
4660
4670
4680
4690
4700
4710
4720
4730
4740
4750
4760
4770
4780
4790
4800
4810
4820
4830
4840
4850
4860
4870
4880
4890
4900
4910
4920
4930
4940
4950
4960
4970
4980
4990
5000
5010
5020
5030
5040
5050
5060
5070
5080
5090
5100
5110
5120
5130
5140
5150
5160
5170
5180
5190
5200
5210
5220
5230
5240
5250
5260
5270
5280
5290
5300
5310
5320
5330
5340
5350
5360
5370
5380
5390
5400
5410
5420
5430
5440
5450
5460
5470
5480
5490
5500
5510
5520
5530
5540
5550
5560
5570
5580
5590
5600
5610
5620
5630
5640
5650
5660
5670
5680
5690
5700
5710
5720
5730
5740
5750
5760
5770
5780
5790
5800
5810
5820
5830
5840
5850
5860
5870
5880
5890
5900
5910
5920
5930
5940
5950
5960
5970
5980
5990
6000
6010
6020
6030
6040
6050
6060
6070
6080
6090
6100
6110
6120
6130
6140
6150
6160
6170
6180
6190
6200
6210
6220
6230
6240
6250
6260
6270
6280
6290
6300
6310
6320
6330
6340
6350
6360
6370
6380
6390
6400
6410
6420
6430
6440
6450
6460
6470
6480
6490
6500
6510
6520
6530
6540
6550
6560
6570
6580
6590
6600
6610
6620
6630
6640
6650
6660
6670
6680
6690
6700
6710
6720
6730
6740
6750
6760
6770
6780
6790
6800
6810
6820
6830
6840
6850
6860
6870
6880
6890
6900
6910
6920
6930
6940
6950
6960
6970
6980
6990
7000
7010
7020
7030
7040
7050
7060
7070
7080
7090
7100
7110
7120
7130
7140
7150
7160
7170
7180
7190
7200
7210
7220
7230
7240
7250
7260
7270
7280
7290
7300
7310
7320
7330
7340
7350
7360
7370
7380
7390
7400
7410
7420
7430
7440
7450
7460
7470
7480
7490
7500
7510
7520
7530
7540
7550
7560
7570
7580
7590
7600
7610
7620
7630
7640
7650
7660
7670
7680
7690
7700
7710
7720
7730
7740
7750
7760
7770
7780
7790
7800
7810
7820
7830
7840
7850
7860
7870
7880
7890
7900
7910
7920
7930
7940
7950
7960
7970
7980
7990
8000
8010
8020
8030
8040
8050
8060
8070
8080
8090
8100
8110
8120
8130
8140
8150
8160
8170
8180
8190
8200
8210
8220
8230
8240
8250
8260
8270
8280
8290
8300
8310
8320
8330
8340
8350
8360
8370
8380
8390
8400
8410
8420
8430
8440
8450
8460
8470
8480
8490
8500
8510
8520
8530
8540
8550
8560
8570
8580
8590
8600
8610
8620
8630
8640
8650
8660
8670
8680
8690
8700
8710
8720
8730
8740
8750
8760
8770
8780
8790
8800
8810
8820
8830
8840
8850
8860
8870
8880
8890
8900
8910
8920
8930
8940
8950
8960
8970
8980
8990
9000
9010
9020
9030
9040
9050
9060
9070
9080
9090
9100
9110
9120
9130
9140
9150
9160
9170
9180
9190
9200
9210
9220
9230
9240
9250
9260
9270
9280
9290
9300
9310
9320
9330
9340
9350
9360
9370
9380
9390
9400
9410
9420
9430
9440
9450
9460
9470
9480
9490
9500
9510
9520
9530
9540
9550
9560
9570
9580
9590
9600
9610
9620
9630
9640
9650
9660
9670
9680
9690
9700
9710
9720
9730
9740
9750
9760
9770
9780
9790
9800
9810
9820
9830
9840
9850
9860
9870
9880
9890
9900
9910
9920
9930
9940
9950
9960
9970
9980
9990
10000
10010
10020
10030
10040
10050
10060
10070
10080
10090
10100
10110
10120
10130
10140
10150
10160
10170
10180
10190
10200
10210
10220
10230
10240
10250
10260
10270
10280
10290
10300
10310
10320
10330
10340
10350
10360
10370
10380
10390
10400
10410
10420
10430
10440
10450
10460
10470
10480
10490
10500
10510
10520
10530
10540
10550
10560

In [42]:
np.save("adj_matrix_2",matrix)

### Creating Node Features

In [46]:
df2 = pd.DataFrame().assign(id=df['id'],race=df['race'],decile_score=df['decile_score'],is_recid=df['is_recid'])
df2

          id              race  decile_score  is_recid
0          1             Other             1         0
1          3  African-American             3         1
2          4  African-American             4         1
3          7             Other             1         0
4          8         Caucasian             6         1
...      ...               ...           ...       ...
10562  11752  African-American             1         1
10563  11753             Other             3         0
10564  11754         Caucasian             7         1
10565  11756         Caucasian             3         0
10566  11757             Asian             1         0

[10567 rows x 4 columns]

In [47]:
df2['race'].value_counts()

African-American    5250
Caucasian           3696
Hispanic             936
Other                599
Asian                 53
Native American       33
Name: race, dtype: int64

In [51]:
df2.loc[df2['race']== 'African-American','race'] = 0
df2.loc[df2['race']== 'Caucasian','race'] = 1
df2.loc[df2['race']== 'Asian','race'] = 2
df2.loc[df2['race']== 'Native American','race'] = 2
df2.loc[df2['race']== 'Hispanic','race'] = 2
df2.loc[df2['race']== 'Other','race'] = 2
df2['race']  = df2['race'].astype('int')
lt =df2[df2['race']==2].index.to_list()
lt
#df2['race'].value_counts()

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/core/ops/array_ops.py:253: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  res_values = method(rvalues)

[0,
 3,
 5,
 17,
 25,
 28,
 38,
 43,
 57,
 64,
 69,
 75,
 78,
 89,
 91,
 93,
 94,
 101,
 116,
 118,
 127,
 135,
 147,
 167,
 171,
 173,
 183,
 192,
 194,
 195,
 217,
 218,
 220,
 237,
 239,
 244,
 246,
 247,
 250,
 251,
 258,
 263,
 275,
 281,
 282,
 284,
 299,
 304,
 311,
 328,
 337,
 341,
 344,
 345,
 351,
 353,
 355,
 361,
 370,
 384,
 389,
 400,
 410,
 416,
 423,
 425,
 428,
 434,
 449,
 456,
 457,
 458,
 461,
 462,
 468,
 473,
 474,
 480,
 483,
 484,
 499,
 501,
 502,
 506,
 527,
 542,
 545,
 549,
 565,
 568,
 576,
 578,
 586,
 593,
 606,
 612,
 615,
 629,
 636,
 653,
 660,
 666,
 668,
 669,
 670,
 677,
 685,
 692,
 695,
 696,
 709,
 711,
 715,
 716,
 720,
 723,
 739,
 745,
 748,
 757,
 763,
 773,
 788,
 796,
 800,
 809,
 812,
 813,
 820,
 821,
 827,
 828,
 835,
 836,
 846,
 847,
 868,
 869,
 872,
 880,
 885,
 894,
 898,
 903,
 913,
 918,
 920,
 924,
 927,
 928,
 939,
 944,
 977,
 987,
 993,
 994,
 1000,
 1003,
 1006,
 1014,
 1016,
 1024,
 1027,
 1047,
 1048,
 1052,
 1059,
 1060,
 1065,
 1066,
 1085,
 1093,
 1095,
 1098,
 1103,
 1109,
 1114,
 1127,
 1137,
 1138,
 1151,
 1158,
 1162,
 1170,
 1173,
 1197,
 1198,
 1204,
 1209,
 1213,
 1216,
 1218,
 1224,
 1225,
 1229,
 1230,
 1231,
 1235,
 1236,
 1247,
 1248,
 1255,
 1268,
 1275,
 1280,
 1281,
 1284,
 1286,
 1290,
 1296,
 1302,
 1322,
 1324,
 1326,
 1328,
 1346,
 1348,
 1358,
 1361,
 1362,
 1365,
 1367,
 1370,
 1372,
 1374,
 1379,
 1384,
 1385,
 1386,
 1389,
 1398,
 1403,
 1404,
 1405,
 1406,
 1412,
 1414,
 1420,
 1422,
 1434,
 1435,
 1439,
 1448,
 1455,
 1464,
 1468,
 1469,
 1488,
 1494,
 1495,
 1504,
 1506,
 1530,
 1538,
 1539,
 1577,
 1586,
 1598,
 1602,
 1611,
 1616,
 1619,
 1622,
 1632,
 1633,
 1634,
 1637,
 1640,
 1641,
 1645,
 1648,
 1653,
 1658,
 1663,
 1686,
 1700,
 1703,
 1704,
 1717,
 1723,
 1742,
 1745,
 1746,
 1751,
 1753,
 1765,
 1769,
 1771,
 1772,
 1780,
 1782,
 1788,
 1793,
 1811,
 1820,
 1823,
 1827,
 1828,
 1840,
 1842,
 1845,
 1858,
 1862,
 1866,
 1871,
 1872,
 1898,
 1899,
 1902,
 1925,
 1926,
 1945,
 1956,
 1961,
 1963,
 1967,
 1993,
 1994,
 2007,
 2017,
 2023,
 2024,
 2032,
 2040,
 2043,
 2049,
 2053,
 2058,
 2062,
 2076,
 2083,
 2085,
 2086,
 2093,
 2098,
 2102,
 2108,
 2112,
 2116,
 2130,
 2132,
 2136,
 2149,
 2150,
 2152,
 2156,
 2163,
 2167,
 2171,
 2175,
 2178,
 2183,
 2200,
 2202,
 2204,
 2214,
 2216,
 2217,
 2230,
 2244,
 2246,
 2251,
 2256,
 2264,
 2265,
 2277,
 2309,
 2310,
 2311,
 2324,
 2325,
 2335,
 2336,
 2342,
 2346,
 2350,
 2360,
 2369,
 2372,
 2382,
 2383,
 2386,
 2387,
 2408,
 2412,
 2430,
 2431,
 2435,
 2449,
 2450,
 2455,
 2456,
 2457,
 2463,
 2464,
 2466,
 2472,
 2484,
 2502,
 2506,
 2520,
 2532,
 2537,
 2545,
 2552,
 2553,
 2558,
 2561,
 2562,
 2564,
 2566,
 2571,
 2577,
 2587,
 2589,
 2594,
 2608,
 2615,
 2639,
 2644,
 2646,
 2663,
 2667,
 2675,
 2681,
 2685,
 2688,
 2692,
 2695,
 2707,
 2710,
 2712,
 2722,
 2725,
 2739,
 2743,
 2753,
 2777,
 2790,
 2792,
 2804,
 2812,
 2813,
 2819,
 2825,
 2830,
 2831,
 2838,
 2845,
 2847,
 2850,
 2853,
 2854,
 2860,
 2871,
 2876,
 2881,
 2883,
 2891,
 2892,
 2893,
 2900,
 2903,
 2906,
 2907,
 2911,
 2926,
 2943,
 2944,
 2947,
 2971,
 2977,
 2979,
 2980,
 2987,
 2994,
 3005,
 3017,
 3043,
 3044,
 3050,
 3054,
 3055,
 3057,
 3071,
 3075,
 3098,
 3117,
 3135,
 3138,
 3140,
 3158,
 3169,
 3174,
 3180,
 3182,
 3183,
 3193,
 3194,
 3208,
 3218,
 3219,
 3220,
 3221,
 3239,
 3243,
 3250,
 3251,
 3257,
 3258,
 3262,
 3265,
 3303,
 3307,
 3309,
 3320,
 3335,
 3348,
 3365,
 3367,
 3369,
 3405,
 3408,
 3449,
 3453,
 3456,
 3462,
 3465,
 3474,
 3475,
 3477,
 3487,
 3495,
 3501,
 3510,
 3513,
 3516,
 3517,
 3518,
 3529,
 3530,
 3533,
 3540,
 3541,
 3542,
 3547,
 3563,
 3566,
 3568,
 3573,
 3575,
 3577,
 3579,
 3587,
 3599,
 3603,
 3605,
 3606,
 3607,
 3608,
 3610,
 3629,
 3633,
 3638,
 3639,
 3641,
 3651,
 3654,
 3665,
 3684,
 3694,
 3708,
 3709,
 3715,
 3718,
 3758,
 3759,
 3761,
 3765,
 3770,
 3777,
 3791,
 3792,
 3793,
 3800,
 3806,
 3809,
 3810,
 3816,
 3817,
 3818,
 3824,
 3841,
 3842,
 3848,
 3855,
 3857,
 3859,
 3866,
 3867,
 3868,
 3870,
 3874,
 3875,
 3890,
 3893,
 3901,
 3902,
 3907,
 3909,
 3921,
 3925,
 3929,
 3933,
 3941,
 3951,
 3957,
 3966,
 3970,
 3974,
 3986,
 3990,
 3993,
 3995,
 4009,
 4014,
 4015,
 4017,
 4024,
 4027,
 4031,
 4038,
 4040,
 4043,
 4044,
 4066,
 4075,
 4077,
 4079,
 4082,
 4101,
 4106,
 4109,
 4121,
 4129,
 4132,
 4133,
 4136,
 4140,
 4147,
 4148,
 4150,
 4164,
 4178,
 4183,
 4184,
 4188,
 4212,
 4214,
 4217,
 4220,
 4224,
 4228,
 4230,
 4231,
 4237,
 4255,
 4258,
 4272,
 4280,
 4285,
 4287,
 4302,
 4318,
 4322,
 4324,
 4326,
 4338,
 4344,
 4356,
 4370,
 4373,
 4376,
 4385,
 4387,
 4403,
 4404,
 4409,
 4410,
 4414,
 4416,
 4423,
 4424,
 4428,
 4437,
 4441,
 4451,
 4457,
 4459,
 4460,
 4463,
 4484,
 4489,
 4492,
 4500,
 4546,
 4555,
 4568,
 4571,
 4575,
 4587,
 4593,
 4600,
 4610,
 4618,
 4628,
 4643,
 4648,
 4655,
 4658,
 4668,
 4669,
 4678,
 4682,
 4688,
 4702,
 4703,
 4711,
 4714,
 4720,
 4726,
 4731,
 4744,
 4746,
 4751,
 4769,
 4771,
 4778,
 4781,
 4813,
 4817,
 4830,
 4831,
 4838,
 4856,
 4861,
 4865,
 4888,
 4891,
 4925,
 4931,
 4938,
 4941,
 4944,
 4949,
 4956,
 4958,
 4961,
 4965,
 4966,
 4976,
 4977,
 4978,
 4992,
 5004,
 5006,
 5012,
 5013,
 5018,
 5039,
 5040,
 5051,
 5066,
 5072,
 5073,
 5075,
 5099,
 5104,
 5106,
 5115,
 5117,
 5129,
 5130,
 5132,
 5134,
 5143,
 5175,
 5188,
 5199,
 5201,
 5202,
 5206,
 5212,
 5213,
 5217,
 5220,
 5222,
 5262,
 5264,
 5280,
 5282,
 5283,
 5293,
 5302,
 5315,
 5326,
 5351,
 5354,
 5357,
 5360,
 5361,
 5362,
 5364,
 5368,
 5369,
 5373,
 5396,
 5397,
 5405,
 5410,
 5413,
 5427,
 5430,
 5435,
 5439,
 5440,
 5443,
 5455,
 5458,
 5461,
 5472,
 5474,
 5476,
 5488,
 5489,
 5517,
 5521,
 5533,
 5535,
 5546,
 5588,
 5590,
 5594,
 5602,
 5607,
 5608,
 5609,
 5614,
 5618,
 5619,
 5620,
 5625,
 5626,
 5628,
 5638,
 5653,
 5659,
 5664,
 5679,
 5683,
 5688,
 5697,
 5698,
 5704,
 5711,
 5712,
 5719,
 5723,
 5725,
 5729,
 5749,
 5750,
 5769,
 5771,
 5778,
 5780,
 5784,
 5788,
 5805,
 5811,
 5816,
 5819,
 5824,
 5840,
 5846,
 5857,
 5866,
 5869,
 5873,
 5878,
 5882,
 5883,
 5884,
 5885,
 5895,
 5901,
 5909,
 5911,
 5912,
 5933,
 5948,
 5954,
 5956,
 5959,
 5992,
 5994,
 6004,
 6006,
 6020,
 6032,
 6034,
 6037,
 6047,
 6048,
 6049,
 6051,
 6057,
 6069,
 6073,
 6082,
 6084,
 6090,
 6095,
 6098,
 6100,
 6101,
 6120,
 6125,
 6131,
 6136,
 6145,
 6146,
 6155,
 6158,
 6161,
 6162,
 6177,
 6181,
 6182,
 6183,
 6187,
 6189,
 6197,
 6203,
 6207,
 6210,
 6213,
 6233,
 6238,
 6252,
 6258,
 6262,
 6265,
 6270,
 6271,
 6275,
 6277,
 6279,
 6280,
 6281,
 6291,
 6293,
 6309,
 6321,
 6327,
 6338,
 6358,
 6369,
 6374,
 6378,
 6382,
 6389,
 6392,
 6398,
 6404,
 6405,
 6410,
 6421,
 6425,
 6427,
 6434,
 6436,
 6453,
 6456,
 6459,
 6463,
 6465,
 6476,
 6500,
 6502,
 6504,
 6507,
 6526,
 6557,
 6558,
 6559,
 6566,
 6567,
 6572,
 6580,
 ...]

In [52]:
df2 = df2[df2['race']<2]
df2 = df2.rename(columns={'decile_score':'s', 'is_recid':'h_c'})
df2

          id  race   s  h_c
1          3     0   3    1
2          4     0   4    1
4          8     1   6    1
6         10     1   1    0
7         11     1  10    0
...      ...   ...  ..  ...
10559  11749     1   7    0
10560  11750     0   1    0
10562  11752     0   1    1
10564  11754     1   7    1
10565  11756     1   3    0

[8946 rows x 4 columns]

In [41]:
df2.to_csv("compas_clean_2.csv", index=False)

In [43]:
df2['h_c'].value_counts()

0    5734
1    3212
Name: h_c, dtype: int64

In [44]:
matrix.shape

(10567, 10567)

In [54]:
matrix = np.delete(matrix,lt,axis=0)
matrix= np.delete(matrix,lt,axis=1)
matrix.shape

(8946, 8946)

In [55]:
np.save("adj_matrix_2",matrix)

In [56]:
np.sum(matrix)

4880630.0